### ISSUE TITLE
Toast Message Issue

### ISSUE THREAD

**Issue by muhammadfarooq012012** [sanzaru/SimpleToast#15]
The message in the toast does not change if we set the global variable for the toast message.

**Comment by sanzaru** [comment]
@muhammadfarooq012012 Could you please provide more information or a short code snippet? I can't reproduce your problem. It's even possible to change the message while the toast is visible, although such things are not recommended.

**Comment by Monkey-X-Byte** [comment]
@State private var toastMessage: String = "xxxx"

.simpleToast(isPresented: $isShowToast, options: SimpleToastOptions(hideAfter: 2)) {
            let _ = print(self.toastMessage)

            HStack {
                Image(systemName: "exclamationmark.triangle")
                Text(toastMessage)
            }
            .padding(EdgeInsets(top: 8, leading: 12, bottom: 8, trailing: 12))
            .background(Color.black)
            .foregroundColor(Color.white)
        }

**Comment by sanzaru** [comment]
@muhammadfarooq012012 
I cannot reproduce the problem. When I create a project with a simple view, a state variable and a textfield, the toast always shows the correct and current value of the variable and even changes while being displayed. In the console the print also shows the current value. 

For me it looks more as if your view is not being updated correctly. The toast itself is not modifying the content to display, so it basically only shows what it gets. How do you set the value of your state variable? 

**I made a recording of my example:**

https://user-images.githubusercontent.com/3462314/159159517-a99ea543-da12-4500-b376-2ca741bd673c.mp4

**Here's the code:**

```swift
import SwiftUI
import SimpleToast

struct ContentView: View {
    @State private var toastMessage = "Some message"
    @State private var showToast = false
    
    var body: some View {
        VStack {
            TextField("", text: $toastMessage)
                .textFieldStyle(RoundedBorderTextFieldStyle())
            
            Button("Toast") { showToast.toggle() }
        }
        .padding()
        .simpleToast(isPresented: $showToast, options: SimpleToastOptions()) {
            let _ = print(self.toastMessage)
            HStack {
                Image(systemName: "exclamationmark.triangle")
                Text(toastMessage)
            }
            .padding(EdgeInsets(top: 8, leading: 12, bottom: 8, trailing: 12))
            .background(Color.black)
            .foregroundColor(Color.white)
        }
    }
}
```

**Comment by Monkey-X-Byte** [comment]
@State private var isShowToast: Bool = false
    @State private var toastMessage: String = "This is some simple toast message."

    var body: some View {
        ZStack {
            VStack {
                Button {
                    self.toastMessage = "Hello world!"
                    let _ = print(self.toastMessage)
                } label: {
                    Text("Change")
                }
                .padding()

                Button {
                    self.isShowToast.toggle()
                } label: {
                    Text("show")
                }
            }
        }
        .simpleToast(isPresented: $isShowToast, options: SimpleToastOptions(hideAfter: 2)) {
            let _ = print(self.toastMessage)
            HStack {
                Image(systemName: "exclamationmark.triangle")
                Text(toastMessage)
            }
            .padding(EdgeInsets(top: 8, leading: 12, bottom: 8, trailing: 12))
            .background(Color.black)
            .foregroundColor(Color.white)
        }
    }



first click change button，then click show button

**Comment by sanzaru** [comment]
@Monkey-X-Byte @muhammadfarooq012012 I can confirm the behavior with your code, although I suspect some SwiftUI / Combine publisher quirks to be the problem. If you simply add a Text to your code, the state variable updates perfectly, also inside the toast:

```swift
ZStack {
        VStack {
            Text(self.toastMessage)

            Button {
                self.toastMessage = "Hello world!"
                let _ = print(self.toastMessage)
```

I will do some more investigation, as this is neither a solution, nor a workaround.

**Comment by Monkey-X-Byte** [comment]
.onChange(of: toastMessage) { newValue in
        }

This can solve the problem, but I don't know why.

**Comment by sanzaru** [comment]
Yeah, it really has to do with publishing and weird pre caching of views. I will investigate deeper this weekend. 

If you call the show before changing the value it works, also removing the if-clause for showing the toast or a simple Text() with the value. Very weird. Hope I can provide a fix, soon.

**Comment by sanzaru** [comment]
@muhammadfarooq012012 @Monkey-X-Byte Release 0.6.2 should fix your issue.
