### ISSUE TITLE
The pop -up speed is too slow

### ISSUE THREAD

**Issue by stakss** [sanzaru/SimpleToast#23]
The pop -up speed is too slow, if it can be configured

**Comment by sanzaru** [comment]
@stakss The library uses the default of the system speed for animations, if not otherwise specified.

You can configure the speed inside the SimpleToastOptions object. The `animation` field defines the animation type and speed which can be overwritten by your own. 

**For example:**
```swift
let optionsDefault = SimpleToastOptions(
      ...
      animation: .easeOut(duration: 0.2),
      ...
  )
```

**Comment by stakss** [comment]
Thanks!
