### ISSUE TITLE
Trigger the display before it is about to disappear, hideAfter is invalid, toast will always exist

### ISSUE THREAD

**Issue by PandaPy** [sanzaru/SimpleToast#24]
Trigger the display before it is about to disappear, hideAfter is invalid, toast will always exist

**Comment by sanzaru** [comment]
@PandaPy Thanks for your feedback. Can you please be more specific how to reproduce the bug you describe and/or provide some code?

**Comment by brooksGetIt** [comment]
same problem, display again when disappear animating,toast will always exist

**Comment by sanzaru** [comment]
@brooksGetIt Thank you for the feedback. Will have a look into it.

**Comment by sanzaru** [comment]
@brooksGetIt @PandaPy The problem should be fixed with version 0.7.2
