### ISSUE TITLE
VisionOS Support?

### ISSUE THREAD

**Issue by jparismorgan** [sanzaru/SimpleToast#37]
Hi there, does this support VisionOS? Would be great to add support and then update the docs, if possible. Thank you!

**Comment by sanzaru** [comment]
@jparismorgan As I'm still waiting for the Vision's release in the EU, I haven't had a chance to test it on a real device. However, I had no issues inside the simulator, so it should work on VisionOS. I will add official support once I've had the chance to test it myself on a real device.

**Comment by sanzaru** [comment]
@jparismorgan I can confirm that the library is running fine on VisionOS natively and in iPad mode.
