### ISSUE TITLE
No such module 'SimpleToast'

### ISSUE THREAD

**Issue by wfs498121294** [sanzaru/SimpleToast#38]
No such module 'SimpleToast'

xcode 15.4
spm

**Comment by sanzaru** [comment]
Could you provide more information?
It sounds like your packages are not loaded correctly. Did you try reloading / updating your packages inside XCode?

**Comment by wfs498121294** [comment]
![Snipaste_2024-10-26_08-51-10](https://github.com/user-attachments/assets/cda4a0c7-164c-42d9-a7dc-767beeceabf6)
![Snipaste_2024-10-26_08-51-59](https://github.com/user-attachments/assets/fbbc3957-c112-4ee6-aed9-db9e18001395)

can you  see pictures

**Comment by wfs498121294** [comment]
![Snipaste_2024-10-26_08-53-00](https://github.com/user-attachments/assets/9d648f1c-e97f-4b2a-be0b-03f7174a34d0)

but i can use in pod

**Comment by sanzaru** [comment]
@wfs498121294 
Thank you for the screenshots and information. It looks like you forgot to add the package to your target when you added it. Please make sure that SimpleToast is listed under "Frameworks, Libraries, and Embedded Content" section on the "General" tab of your target:

![SimpleToast-XCode](https://github.com/user-attachments/assets/e9edb9d5-bdc6-465f-a1e3-63474b159d4b)

If the package is not listed there you need to add it via the plus button.

**Comment by wfs498121294** [comment]
thinaks
