### ISSUE TITLE
alignment

### ISSUE THREAD

**Issue by navid-sharifi** [sanzaru/SimpleToast#39]
i can't see the "alignment" in Option , version 0.8.1

**Comment by sanzaru** [comment]
@navid-sharifi The alignment parameter in the SimpleToastOptions struct is still available: https://github.com/sanzaru/SimpleToast/blob/8dbc2e7c33cda25c0b2efafd59716cb9820c83eb/Sources/SimpleToast/SimpleToastOptions.swift#L14

Can you provide a snippet of code where you implemented the options?

**Comment by navid-sharifi** [comment]
> @navid-sharifi The alignment parameter in the SimpleToastOptions struct is still available:
> 
> https://github.com/sanzaru/SimpleToast/blob/8dbc2e7c33cda25c0b2efafd59716cb9820c83eb/Sources/SimpleToast/SimpleToastOptions.swift#L14
> 
> Can you provide a snippet of code where you implemented the options?

it work as well  , thank you
but the Alignment must be first.

private let toastOptions = SimpleToastOptions(
        alignment : .center,
        hideAfter: 3 ,
        animation: .smooth,
        modifierType: .scale
    )
